# data.py — All static reference data for RamsTech

FAULT_CODES = {
    "P0101":{"code":"P0101","description":"Mass Air Flow Circuit","system":"Engine","severity":"Medium",
             "causes":["Dirty MAF","Air leaks","Clogged filter"],"symptoms":["Poor economy","Loss of power"],
             "steps":["Check filter","Inspect intake","Clean MAF"]},
    "P0300":{"code":"P0300","description":"Multiple Cylinder Misfire","system":"Engine","severity":"High",
             "causes":["Faulty plugs","Bad coils","Fuel issues"],"symptoms":["Engine shaking","Loss of power"],
             "steps":["Scan cylinders","Check plugs","Test coils"]},
    "P0401":{"code":"P0401","description":"EGR Flow Insufficient","system":"Engine","severity":"Medium",
             "causes":["Clogged EGR","Blocked passages"],"symptoms":["Check engine light"],
             "steps":["Inspect EGR","Check passages"]},
    "P0700":{"code":"P0700","description":"Transmission Control System","system":"Transmission","severity":"High",
             "causes":["Internal fault","TCM problem"],"symptoms":["Slipping","Harsh shifting"],
             "steps":["Scan TCM","Check fluid"]},
    "P0087":{"code":"P0087","description":"Fuel Rail Pressure Low","system":"Diesel","severity":"High",
             "causes":["Faulty HP pump","Clogged filter"],"symptoms":["Won't start","Loss of power"],
             "steps":["Check pressure","Inspect filter"]},
    "HYD-001":{"code":"HYD-001","description":"Low Hydraulic Pressure","system":"Hydraulic","severity":"High",
               "causes":["Worn pump","Leaks","Low fluid"],"symptoms":["Slow operation","Weak lifting"],
               "steps":["Check fluid","Test pressure"]},
    "PNEU-001":{"code":"PNEU-001","description":"Air Compressor No Pressure","system":"Pneumatic","severity":"High",
                "causes":["Worn rings","Leaking valves"],"symptoms":["Low pressure"],
                "steps":["Check belt","Test output"]},
}

WMI_DB = {"1HG":("Honda","USA"),"1FT":("Ford","USA"),"JHM":("Honda","Japan"),
          "JTD":("Toyota","Japan"),"JTM":("Toyota","Japan"),"KMH":("Hyundai","Korea"),
          "KNA":("Kia","Korea"),"WBA":("BMW","Germany"),"WDB":("Mercedes-Benz","Germany"),
          "WVW":("Volkswagen","Germany"),"AHT":("Toyota SA","South Africa"),"ADB":("Mercedes SA","South Africa")}

YEAR_CODES = {"A":2010,"B":2011,"C":2012,"D":2013,"E":2014,"F":2015,"G":2016,"H":2017,
              "J":2018,"K":2019,"L":2020,"M":2021,"N":2022,"P":2023,"R":2024,
              "Y":2000,"1":2001,"2":2002,"3":2003,"4":2004}

TORQUE_SPECS = [
    {"size":"M6","grade":"8.8","nm":10,"ftlb":7.4,"use":"Small brackets"},
    {"size":"M8","grade":"8.8","nm":25,"ftlb":18.4,"use":"Engine brackets"},
    {"size":"M10","grade":"8.8","nm":50,"ftlb":37,"use":"Subframe bolts"},
    {"size":"M12","grade":"8.8","nm":90,"ftlb":66,"use":"Wheel hubs"},
    {"size":"M14","grade":"8.8","nm":140,"ftlb":103,"use":"Heavy brackets"},
    {"size":"M16","grade":"8.8","nm":215,"ftlb":159,"use":"Chassis bolts"},
    {"size":"M20","grade":"8.8","nm":425,"ftlb":313,"use":"Truck chassis"},
    {"size":"M8","grade":"10.9","nm":35,"ftlb":25.8,"use":"Cylinder head (small)"},
    {"size":"M10","grade":"10.9","nm":70,"ftlb":51.6,"use":"Cylinder head bolts"},
    {"size":"M12","grade":"10.9","nm":120,"ftlb":88.5,"use":"Head bolts"},
    {"size":"M14","grade":"10.9","nm":190,"ftlb":140,"use":"Head (diesel)"},
    {"size":"M16","grade":"10.9","nm":295,"ftlb":218,"use":"Heavy diesel"},
    {"size":"M12","grade":"12.9","nm":145,"ftlb":107,"use":"Racing"},
    {"size":"M10","grade":"12.9","nm":83,"ftlb":61.2,"use":"Performance"},
]

TORQUE_SEQUENCES = [
    {"component":"Cylinder Head — 4 Cyl","pattern":"Star","steps":["Stage 1: 40 Nm","Stage 2: 80 Nm","Stage 3: +90°","Stage 4: +90°"],"note":"Replace TTY bolts."},
    {"component":"Wheel Nuts — Car","pattern":"Star","steps":["Stage 1: 60 Nm","Final: 110 Nm"],"note":"Re-torque after 50-100 km."},
    {"component":"Wheel Nuts — Bakkie","pattern":"Star","steps":["Stage 1: 100 Nm","Final: 140 Nm"],"note":"Hilux, Ranger, Amarok."},
    {"component":"Wheel Nuts — Truck","pattern":"Star","steps":["Stage 1: 400 Nm","Stage 2: 500 Nm","Final: 600 Nm"],"note":"10-stud."},
    {"component":"Spark Plugs","pattern":"Linear","steps":["Cast iron: 25 Nm","Aluminum: 18 Nm"],"note":"Do NOT overtighten."},
    {"component":"Oil Drain Plug","pattern":"Linear","steps":["Steel M12: 25 Nm","Alum M12: 18 Nm"],"note":"Replace washer."},
]

PARTS_CATALOG = [
    {"number":"04152-YZZA1","name":"Oil Filter","brand":"Toyota","category":"Engine","price":15},
    {"number":"17801-30060","name":"Air Filter","brand":"Toyota","category":"Engine","price":25},
    {"number":"04465-YZZE8","name":"Brake Pads Front","brand":"Toyota","category":"Brakes","price":55},
    {"number":"04466-YZZE8","name":"Brake Pads Rear","brand":"Toyota","category":"Brakes","price":45},
    {"number":"23390-30020","name":"Fuel Filter","brand":"Toyota","category":"Fuel","price":35},
    {"number":"90919-01253","name":"Spark Plug","brand":"Toyota","category":"Ignition","price":12},
    {"number":"26300-35505","name":"Oil Filter","brand":"Hyundai","category":"Engine","price":14},
    {"number":"58101-2EA00","name":"Brake Pads","brand":"Hyundai","category":"Brakes","price":50},
    {"number":"BK-4E","name":"Battery Terminal","brand":"Universal","category":"Electrical","price":8},
    {"number":"HF-1","name":"Hydraulic Filter","brand":"Universal","category":"Hydraulic","price":45},
    {"number":"AF-220","name":"Air Filter (heavy)","brand":"Universal","category":"Pneumatic","price":60},
    {"number":"WABCO-4324100202","name":"Air Dryer Cartridge","brand":"WABCO","category":"Pneumatic","price":85},
    {"number":"BOSCH-F026T02025","name":"Fuel Filter","brand":"Bosch","category":"Diesel","price":40},
    {"number":"MANN-WK940/20","name":"Diesel Filter","brand":"MANN","category":"Diesel","price":38},
    {"number":"GATES-6PK1250","name":"Serpentine Belt","brand":"Gates","category":"Engine","price":65},
    {"number":"NGK-BKR6EIX","name":"Iridium Plug","brand":"NGK","category":"Ignition","price":18},
    {"number":"DELPHI-CF1022","name":"Fuel Pump","brand":"Delphi","category":"Fuel","price":220},
]

COMMON_PROBLEMS = [
    {"title":"Engine won't start (cranks)","system":"Engine","severity":"High",
     "causes":["No fuel","No spark","Low compression"],"checks":["Check fuel pressure","Test spark","Compression test"]},
    {"title":"Overheating","system":"Cooling","severity":"Critical",
     "causes":["Low coolant","Thermostat","Water pump"],"checks":["Check coolant","Test thermostat","Check pump"]},
    {"title":"Misfire at idle","system":"Engine","severity":"Medium",
     "causes":["Spark plugs","Coils","Vacuum leak"],"checks":["Scan codes","Check plugs","Smoke test"]},
    {"title":"White smoke (diesel)","system":"Diesel","severity":"High",
     "causes":["Injector timing","Coolant leak","Glow plugs"],"checks":["Check coolant","Test injectors","Compression"]},
    {"title":"Black smoke (diesel)","system":"Diesel","severity":"Medium",
     "causes":["Over-fuelling","Air filter","Turbo"],"checks":["Check air filter","Test turbo","Injectors"]},
    {"title":"Transmission slipping","system":"Transmission","severity":"High",
     "causes":["Low fluid","Worn clutches","Solenoid"],"checks":["Check fluid","Scan TCM","Test pressure"]},
    {"title":"Brake pedal soft","system":"Brakes","severity":"Critical",
     "causes":["Air in system","Fluid leak","Master cylinder"],"checks":["Bleed brakes","Check leaks","Test master"]},
    {"title":"ABS light on","system":"Brakes","severity":"High",
     "causes":["Wheel speed sensor","Tone ring","Wiring"],"checks":["Scan codes","Check sensors","Inspect ring"]},
    {"title":"Battery drains overnight","system":"Electrical","severity":"Medium",
     "causes":["Parasitic draw","Alternator","Old battery"],"checks":["Check draw","Test alternator","Load test"]},
    {"title":"Low hydraulic power","system":"Hydraulic","severity":"High",
     "causes":["Low fluid","Worn pump","Internal leak"],"checks":["Check fluid","Test pressure","Check leaks"]},
    {"title":"Air compressor no pressure","system":"Pneumatic","severity":"High",
     "causes":["Worn rings","Leaking valves","Air leaks"],"checks":["Check belt","Test pressure","Check leaks"]},
    {"title":"Rough idle","system":"Engine","severity":"Medium",
     "causes":["Vacuum leak","Dirty throttle","MAF"],"checks":["Smoke test","Clean throttle","Clean MAF"]},
    {"title":"Grinding when braking","system":"Brakes","severity":"High",
     "causes":["Worn pads","Warped rotor","Worn bearings"],"checks":["Inspect pads","Check rotor","Check bearings"]},
    {"title":"Stuck in limp mode","system":"Transmission","severity":"High",
     "causes":["Sensor fault","Wiring","TCM"],"checks":["Scan codes","Check wiring","Test sensors"]},
]

WIRING_LIBRARY = [
    {"id":"WD001","name":"Charging System","system":"Charging","description":"Alternator, battery, warning light",
     "components":["Battery 12V","Alternator (B+, D+, S, W)","Ignition switch","Charge warning light"],
     "connections":["Battery + → Alt B+ (Red, 6mm²)","Battery - → Ground (Black, 10mm²)","Alt D+ → Warning light"],
     "notes":["Output: 13.8-14.4V","Warning light ON with engine off is normal"]},
    {"id":"WD002","name":"Starting System","system":"Starting","description":"Starter motor, relay, ignition",
     "components":["Battery","Ignition switch","Starter relay","Starter motor"],
     "connections":["Battery + → Starter 30 (Red, 25mm²)","IGN 50 → Relay 86 (Yellow)","Relay 87 → Starter 50"],
     "notes":["Don't hold starter over 10 sec"]},
    {"id":"WD003","name":"Engine Sensors","system":"Engine","description":"MAF, MAP, TPS, ECT, O2",
     "components":["ECU","MAF","MAP","TPS","ECT","O2"],
     "connections":["ECU → MAF: signal+ground+power","ECU → MAP: signal+ground+5V","ECU → TPS: 5V+signal+ground"],
     "notes":["Reference: 4.9-5.1V","MAF: 0.5-4.5V"]},
    {"id":"WD004","name":"Headlight Circuit","system":"Lighting","description":"Relay-controlled headlights",
     "components":["Battery","Headlight switch","Low relay","High relay","Headlights"],
     "connections":["Battery + → Relay 30 (Red)","Switch 56 → Relay 86","Relay 87 → Headlight +"],
     "notes":["Voltage drop < 0.5V"]},
    {"id":"WD005","name":"ABS Wheel Sensors","system":"ABS","description":"4-channel wheel speed",
     "components":["ABS ECU","FL/FR/RL/RR sensors","Pump motor"],
     "connections":["ABS → FL (White+Black)","ABS → FR (Yellow+Green)","ABS → RL (Blue+Grey)","ABS → RR (Brown+Purple)"],
     "notes":["Resistance: 800-1400Ω"]},
    {"id":"WD006","name":"Diesel Glow Plugs","system":"Diesel","description":"Glow relay circuit",
     "components":["Battery","Ignition","Glow relay","Glow plugs 1-4"],
     "connections":["Battery + → Relay 30","IGN 15 → Relay 86","Relay 87 → All glow plugs"],
     "notes":["Resistance: 0.5-2Ω"]},
    {"id":"WD007","name":"Transmission Control","system":"Transmission","description":"TCM, solenoids, sensors",
     "components":["TCM","Shift solenoids","Line pressure solenoid","Speed sensors"],
     "connections":["TCM → Sol A (Red)","TCM → Sol B (Blue)","TCM → Line pressure (Yellow)"],
     "notes":["Solenoid: 10-15Ω"]},
    {"id":"WD008","name":"Petrol Fuel Injection","system":"Fuel","description":"Injectors and pump",
     "components":["ECU","Injectors 1-4","Fuel pump relay","Fuel pump"],
     "connections":["ECU → Injector drivers","ECU → Relay 86","Relay 87 → Fuel pump"],
     "notes":["Injector: 12-16Ω"]},
    {"id":"WD009","name":"CAN Bus Network","system":"Network","description":"Multi-module bus",
     "components":["ECM","TCM","BCM","ABS","DLC"],
     "connections":["All: CAN-H (Yellow)","All: CAN-L (Green)","DLC pin 6=H, pin 14=L"],
     "notes":["Termination: 60Ω"]},
    {"id":"WD010","name":"Immobilizer","system":"Security","description":"Key transponder",
     "components":["IMMO ECU","Antenna","Status LED","ECM"],
     "connections":["IMMO → Antenna","IMMO → ECM (CAN)","IMMO → LED"],
     "notes":["Antenna: 5-20Ω"]},
]

OBD_PIDS = [
    {"pid":"0100","name":"PIDs supported 1-20","desc":"Bit-encoded supported"},
    {"pid":"0101","name":"Monitor status","desc":"MIL status"},
    {"pid":"0103","name":"Fuel system status","desc":"Open/closed loop"},
    {"pid":"0104","name":"Calculated engine load","desc":"% of max"},
    {"pid":"0105","name":"Engine coolant temp","desc":"°C"},
    {"pid":"0106","name":"Short fuel trim B1","desc":"% correction"},
    {"pid":"0107","name":"Long fuel trim B1","desc":"% correction"},
    {"pid":"010B","name":"Intake manifold pressure","desc":"kPa"},
    {"pid":"010C","name":"Engine RPM","desc":"((A*256)+B)/4"},
    {"pid":"010D","name":"Vehicle speed","desc":"km/h"},
    {"pid":"010E","name":"Timing advance","desc":"° BTDC"},
    {"pid":"010F","name":"Intake air temp","desc":"°C"},
    {"pid":"0110","name":"MAF air flow rate","desc":"g/s"},
    {"pid":"0111","name":"Throttle position","desc":"%"},
    {"pid":"011F","name":"Run time since start","desc":"seconds"},
    {"pid":"0121","name":"Distance with MIL on","desc":"km"},
    {"pid":"012F","name":"Fuel level","desc":"%"},
    {"pid":"0131","name":"Distance since cleared","desc":"km"},
    {"pid":"0133","name":"Barometric pressure","desc":"kPa"},
    {"pid":"0142","name":"Control module voltage","desc":"V"},
    {"pid":"0146","name":"Ambient air temp","desc":"°C"},
    {"pid":"015C","name":"Engine oil temp","desc":"°C"},
]

BULB_CHART = [
    {"vehicle":"Toyota Hilux (2015+)","headlight_low":"H11","headlight_high":"HB3","fog":"H16","interior":"W5W","reverse":"W16W"},
    {"vehicle":"Ford Ranger","headlight_low":"H11","headlight_high":"HB3","fog":"H11","interior":"W5W","reverse":"P21W"},
    {"vehicle":"VW Polo","headlight_low":"H7","headlight_high":"H7","fog":"H8","interior":"W5W","reverse":"P21W"},
    {"vehicle":"BMW 3-Series","headlight_low":"H7 / Xenon","headlight_high":"H7","fog":"H8","interior":"W5W","reverse":"P21W"},
    {"vehicle":"Mercedes C-Class","headlight_low":"H7 / Xenon","headlight_high":"H7","fog":"H11","interior":"W5W","reverse":"P21W"},
    {"vehicle":"Isuzu D-Max","headlight_low":"H11","headlight_high":"HB3","fog":"H11","interior":"W5W","reverse":"P21W"},
    {"vehicle":"Nissan NP200","headlight_low":"H4","headlight_high":"H4","fog":"H11","interior":"W5W","reverse":"P21W"},
    {"vehicle":"Hyundai i20","headlight_low":"H7","headlight_high":"H7","fog":"H27W","interior":"W5W","reverse":"P21W"},
]

BATTERY_SIZES = [
    {"vehicle":"Toyota Hilux 2.8 GD-6","group":"DIN 66L","cca":680,"ah":70,"terminal":"European"},
    {"vehicle":"Ford Ranger 2.2 TDCi","group":"DIN 66L","cca":660,"ah":68,"terminal":"European"},
    {"vehicle":"VW Polo / Golf","group":"DIN 44L","cca":330,"ah":44,"terminal":"European"},
    {"vehicle":"BMW 3-Series","group":"DIN 80L","cca":800,"ah":80,"terminal":"European"},
    {"vehicle":"Mercedes C-Class","group":"DIN 80L","cca":800,"ah":80,"terminal":"European"},
    {"vehicle":"Isuzu D-Max","group":"DIN 66L","cca":650,"ah":68,"terminal":"European"},
    {"vehicle":"Land Cruiser 79","group":"DIN 88L ×2","cca":880,"ah":90,"terminal":"European"},
    {"vehicle":"Hyundai i20","group":"DIN 44L","cca":350,"ah":45,"terminal":"European"},
    {"vehicle":"Nissan Navara","group":"DIN 66L","cca":640,"ah":65,"terminal":"European"},
    {"vehicle":"Small bakkies","group":"24F / 24R","cca":500,"ah":55,"terminal":"Japanese"},
]

TYRE_SIZES = [
    {"vehicle":"Toyota Hilux (current)","size":"265/65R17","pressure_f":"2.2 bar","pressure_r":"2.4 bar"},
    {"vehicle":"Toyota Hilux (older)","size":"265/70R16","pressure_f":"2.0 bar","pressure_r":"2.2 bar"},
    {"vehicle":"Ford Ranger","size":"265/65R17","pressure_f":"2.2 bar","pressure_r":"2.4 bar"},
    {"vehicle":"VW Polo","size":"185/60R15","pressure_f":"2.1 bar","pressure_r":"2.1 bar"},
    {"vehicle":"VW Golf 7","size":"205/55R16","pressure_f":"2.3 bar","pressure_r":"2.3 bar"},
    {"vehicle":"BMW 3-Series","size":"225/45R18","pressure_f":"2.4 bar","pressure_r":"2.6 bar"},
    {"vehicle":"Mercedes C-Class","size":"225/50R17","pressure_f":"2.3 bar","pressure_r":"2.5 bar"},
    {"vehicle":"Hyundai i20","size":"185/65R15","pressure_f":"2.2 bar","pressure_r":"2.2 bar"},
    {"vehicle":"Nissan NP200","size":"185/65R15","pressure_f":"2.0 bar","pressure_r":"2.2 bar"},
]

FUSE_BOXES = [
    {"vehicle":"Toyota Hilux (2015+)","location":"Engine bay + under-dash",
     "common":["7.5A - ECU","15A - Fuel pump","10A - Headlight LH","10A - Headlight RH","20A - Wiper","30A - ABS pump"]},
    {"vehicle":"Ford Ranger","location":"Engine bay + kick panel",
     "common":["10A - ECU","15A - Injectors","20A - Fuel pump","30A - Cooling fan"]},
    {"vehicle":"VW Polo/Golf","location":"Driver dash + engine bay",
     "common":["5A - BCM","10A - Lights","15A - Fuel pump","30A - ABS"]},
    {"vehicle":"BMW 3-Series","location":"Glove box + boot",
     "common":["5A - Electronics","15A - Fuel pump","30A - Cooling fan","40A - ABS"]},
]

PRE_PURCHASE_CHECKLIST = [
    "VIN matches paperwork","Engine number matches","Service history present",
    "Odometer matches condition","Body panels align","Paint colour consistent",
    "No overspray on trim","Tyres same brand + tread >4mm","Spare wheel + jack present",
    "No warning lights","All lights work","Wipers + washers work","Horn works",
    "Hazard lights work","Radio/speakers work","Aircon blows cold","Heater blows hot",
    "All windows wind up/down","Mirrors adjust","Seats adjust","Seatbelts retract",
    "Doors lock/unlock","Boot opens","Bonnet latch works","No oil leaks","No coolant leaks",
    "Brake fluid level OK","Power steering fluid OK","Engine starts cold (no rattle)",
    "No blue/white smoke","No black smoke when revved","Transmission shifts smoothly",
    "Clutch bites properly","Brakes stop straight","No vibrations at speed",
    "Steering feels tight","Suspension quiet over bumps","No rust underneath",
    "Exhaust sounds normal","Battery holds charge","Alternator charges 13.8-14.4V",
]

ROADWORTHY_CHECKLIST = [
    "Registration certificate present","VIN plate legible","Engine number legible",
    "All lights functional","Brake lights work","Indicators work","Reverse lights work",
    "Hazard lights work","Number plate lights work","Headlight aim correct",
    "Windscreen no cracks in driver view","Wipers functional","Washer works","Horn works",
    "Mirrors present + secure","Seatbelts functional","Brake pedal firm","Handbrake holds",
    "Brake pads >3mm","Tyre tread >1mm","No sidewall damage","No exposed cords",
    "Wheel nuts tight","Suspension no knocking","Shocks not leaking","Steering no play",
    "Exhaust no leaks","Emissions within limits","Fuel cap seals","No fluid leaks",
    "Battery secured","Battery terminals clean","No warning lights","Speedometer works",
    "Doors open/close from inside","Windows function","Boot closes securely","Sun visors present",
]

INSPECTION_CATEGORIES = {
    "pre_purchase": {"name":"Pre-Purchase Inspection","items":PRE_PURCHASE_CHECKLIST},
    "roadworthy": {"name":"Roadworthy Checklist","items":ROADWORTHY_CHECKLIST},
}

SERVICE_INTERVALS = {
    "petrol": {"km":15000,"months":12,"items":["Oil + filter","Air filter check","Spark plugs check","Brake inspection"]},
    "diesel": {"km":10000,"months":6,"items":["Oil + filter","Fuel filter","Air filter","Water separator drain"]},
    "truck_diesel": {"km":25000,"months":6,"items":["Oil + filters","Fuel filter","Air dryer","Brake check"]},
    "motorcycle": {"km":6000,"months":6,"items":["Oil + filter","Chain lube","Brake check"]},
}

# ═══════════════════════════════════
# TRANSLATIONS (v9.0)
# ═══════════════════════════════════
TRANSLATIONS = {
    "en": {
        "home":"Home","dashboard":"Dashboard","chat":"AI Chat","codes":"Codes","problems":"Problems",
        "vin":"VIN","paint":"Paint","photo":"Photo Diag","jobs":"Jobs","customers":"Customers",
        "appointments":"Appointments","quotes":"Quotes","invoices":"Invoices","parts":"Parts",
        "inventory":"Inventory","purchase":"Purchase","staff":"Staff","clockin":"Clock In/Out",
        "expenses":"Expenses","reminders":"Reminders","wiring":"Wiring","obd":"OBD-II",
        "bulbs":"Bulbs","batteries":"Batteries","tyres":"Tyres","fuses":"Fuses",
        "service":"Service Calc","inspect":"Inspect","boltcalc":"Bolt Calc","torque":"Torque",
        "history":"History","analytics":"Analytics","tax":"Tax","fuel":"Fuel Log",
        "warranty":"Warranty","settings":"Settings",
        "new_job":"+ New Job","new_customer":"+ New Customer","export_csv":"📥 CSV",
        "save":"Save","cancel":"Cancel","delete":"Delete","print":"Print","edit":"Edit",
        "total":"Total","subtotal":"Subtotal","customer":"Customer","vehicle":"Vehicle",
        "phone":"Phone","email":"Email","address":"Address","status":"Status","date":"Date",
        "amount":"Amount","notes":"Notes","category":"Category","save_settings":"Save Settings",
        "signature":"Signature","sign_here":"Sign here","clear":"Clear","confirm":"Confirm"
    },
    "af": {
        "home":"Tuis","dashboard":"Paneel","chat":"KI Gesels","codes":"Kodes","problems":"Probleme",
        "vin":"VIN","paint":"Verf","photo":"Foto Diag","jobs":"Werk","customers":"Kliënte",
        "appointments":"Afsprake","quotes":"Kwotasies","invoices":"Fakture","parts":"Onderdele",
        "inventory":"Voorraad","purchase":"Aankope","staff":"Personeel","clockin":"Klok In/Uit",
        "expenses":"Uitgawes","reminders":"Herinneringe","wiring":"Bedrading","obd":"OBD-II",
        "bulbs":"Gloeilampe","batteries":"Batterye","tyres":"Bande","fuses":"Sekeringe",
        "service":"Diens Bereken","inspect":"Inspeksie","boltcalc":"Bout Bereken","torque":"Wringkrag",
        "history":"Geskiedenis","analytics":"Analise","tax":"Belasting","fuel":"Brandstof",
        "warranty":"Waarborg","settings":"Instellings",
        "new_job":"+ Nuwe Werk","new_customer":"+ Nuwe Kliënt","export_csv":"📥 CSV",
        "save":"Stoor","cancel":"Kanselleer","delete":"Verwyder","print":"Druk","edit":"Wysig",
        "total":"Totaal","subtotal":"Subtotaal","customer":"Kliënt","vehicle":"Voertuig",
        "phone":"Foon","email":"E-pos","address":"Adres","status":"Status","date":"Datum",
        "amount":"Bedrag","notes":"Notas","category":"Kategorie","save_settings":"Stoor",
        "signature":"Handtekening","sign_here":"Teken hier","clear":"Vee uit","confirm":"Bevestig"
    },
    "zu": {
        "home":"Ikhaya","dashboard":"Ideshibhodi","chat":"I-AI","codes":"Amakhodi","problems":"Izinkinga",
        "vin":"I-VIN","paint":"Upende","photo":"Isithombe","jobs":"Imisebenzi","customers":"Amaklayenti",
        "appointments":"Izikhathi","quotes":"Izilinganiso","invoices":"Ama-invoyisi","parts":"Izingxenye",
        "inventory":"Impahla","purchase":"Ukuthenga","staff":"Abasebenzi","clockin":"Isikhathi",
        "expenses":"Izindleko","reminders":"Izikhumbuzo","wiring":"Izintambo","obd":"I-OBD",
        "bulbs":"Amabhalbhu","batteries":"Amabhethri","tyres":"Amathayi","fuses":"Amafuse",
        "service":"Inkonzo","inspect":"Ukuhlola","boltcalc":"Ibhawodi","torque":"I-Torque",
        "history":"Umlando","analytics":"Ukuhlaziya","tax":"Intela","fuel":"Uphathi",
        "warranty":"Iwaranti","settings":"Izilungiselelo",
        "new_job":"+ Umsebenzi Omusha","new_customer":"+ Iklayenti Elisha","export_csv":"📥 CSV",
        "save":"Gcina","cancel":"Khansela","delete":"Susa","print":"Phrinta","edit":"Hlela",
        "total":"Isamba","subtotal":"Ingxenye","customer":"Iklayenti","vehicle":"Imoto",
        "phone":"Ucingo","email":"I-imeyili","address":"Ikheli","status":"Isimo","date":"Usuku",
        "amount":"Inani","notes":"Amanothi","category":"Isigaba","save_settings":"Gcina",
        "signature":"Isiginesha","sign_here":"Sayina lapha","clear":"Sula","confirm":"Qinisekisa"
    }
}
