P3 = r"""
<script>
const CATEGORIES = {
diagnostics:{name:'Diagnostics',icon:'🔧',gradient:'linear-gradient(135deg,#2196F3,#0d47a1)',
items:[{icon:'🤖',label:'AI Chat',tab:'chat',color:'#3b82f6'},{icon:'📟',label:'Fault Codes',tab:'codes',color:'#ef4444'},{icon:'📖',label:'Problems',tab:'problems',color:'#f59e0b'},{icon:'🔍',label:'VIN Decoder',tab:'vin',color:'#8b5cf6'},{icon:'🎨',label:'Paint Match',tab:'paint',color:'#ec4899'},{icon:'📸',label:'Photo Diag',tab:'photo',color:'#06b6d4'}]},
workshop:{name:'Workshop',icon:'📋',gradient:'linear-gradient(135deg,#f59e0b,#dc2626)',
items:[{icon:'📋',label:'Jobs',tab:'jobs',color:'#f59e0b'},{icon:'👥',label:'Customers',tab:'customers',color:'#10b981'},{icon:'📅',label:'Appointments',tab:'appointments',color:'#3b82f6'},{icon:'💬',label:'Quotes',tab:'quotes',color:'#8b5cf6'},{icon:'💰',label:'Invoices',tab:'invoices',color:'#10b981'}]},
operations:{name:'Operations',icon:'⚙️',gradient:'linear-gradient(135deg,#10b981,#047857)',
items:[{icon:'📦',label:'Inventory',tab:'inventory',color:'#f59e0b'},{icon:'🛒',label:'Purchase',tab:'purchase',color:'#3b82f6'},{icon:'👷',label:'Staff',tab:'staff',color:'#10b981'},{icon:'🕐',label:'Clock In/Out',tab:'clockin',color:'#8b5cf6'},{icon:'💸',label:'Expenses',tab:'expenses',color:'#ef4444'},{icon:'⛽',label:'Fuel Log',tab:'fuel',color:'#f59e0b'},{icon:'🎁',label:'Warranty',tab:'warranty',color:'#ec4899'},{icon:'🗓️',label:'Reminders',tab:'reminders',color:'#06b6d4'}]},
reference:{name:'Reference',icon:'📚',gradient:'linear-gradient(135deg,#8b5cf6,#4c1d95)',
items:[{icon:'🔩',label:'Parts',tab:'parts',color:'#6b7280'},{icon:'🔌',label:'Wiring',tab:'wiring',color:'#f59e0b'},{icon:'⚡',label:'OBD-II',tab:'obd',color:'#eab308'},{icon:'💡',label:'Bulbs',tab:'bulbs',color:'#f59e0b'},{icon:'🔋',label:'Batteries',tab:'batteries',color:'#10b981'},{icon:'🛞',label:'Tyres',tab:'tyres',color:'#1f2937'},{icon:'🔌',label:'Fuses',tab:'fuses',color:'#ef4444'},{icon:'⏰',label:'Service Calc',tab:'service',color:'#3b82f6'},{icon:'✅',label:'Inspect',tab:'inspect',color:'#10b981'},{icon:'🔧',label:'Bolt Calc',tab:'boltcalc',color:'#8b5cf6'},{icon:'⚙️',label:'Torque',tab:'torque',color:'#ec4899'}]},
business:{name:'Business',icon:'💼',gradient:'linear-gradient(135deg,#1f2937,#4b5563)',
items:[{icon:'📊',label:'Dashboard',tab:'dashboard',color:'#3b82f6'},{icon:'🚗',label:'History',tab:'history',color:'#10b981'},{icon:'📈',label:'Analytics',tab:'analytics',color:'#8b5cf6'},{icon:'🧾',label:'Tax',tab:'tax',color:'#f59e0b'},{icon:'⚙️',label:'Settings',tab:'settings',color:'#6b7280'}]}
};
document.getElementById('categoryGrid').innerHTML=Object.entries(CATEGORIES).map(([k,c])=>`<div class="cat-card" style="background:${c.gradient}" onclick="openCategory('${k}')"><div class="cat-icon">${c.icon}</div><div class="cat-info"><div class="cat-name">${c.name}</div><div class="cat-count">${c.items.length} features</div></div><div class="cat-arrow">›</div></div>`).join('');
function openCategory(k){const c=CATEGORIES[k];document.getElementById('categoryView').style.display='none';document.getElementById('subView').style.display='block';document.getElementById('subTitle').textContent=c.icon+' '+c.name;document.getElementById('subGrid').innerHTML=c.items.map(i=>`<div class="tile" onclick="showTab('${i.tab}')"><div class="tile-accent" style="background:${i.color}"></div><div class="tile-icon">${i.icon}</div><div class="tile-label">${i.label}</div></div>`).join('');window.scrollTo(0,0);}
function backToCategories(){document.getElementById('subView').style.display='none';document.getElementById('categoryView').style.display='block';window.scrollTo(0,0);}
function showTab(name,el){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.bnav-item').forEach(t=>t.classList.remove('active'));const panel=document.getElementById(name);if(panel)panel.classList.add('active');if(el)el.classList.add('active');window.scrollTo(0,0);
const loaders={codes:()=>!document.getElementById('codeResults').dataset.loaded&&searchCodes(),problems:()=>!document.getElementById('problemList').dataset.loaded&&loadProblems(),jobs:()=>{loadJobs();loadStaffDropdown();},customers:loadCustomers,appointments:loadAppts,quotes:loadQuotes,invoices:loadInvoices,parts:()=>!document.getElementById('partsList').dataset.loaded&&loadParts(),inventory:loadInventory,purchase:loadPOs,staff:loadStaff,clockin:loadClockin,expenses:loadExpenses,fuel:loadFuel,warranty:loadWarranty,reminders:loadReminders,wiring:loadWiring,obd:loadOBD,bulbs:loadBulbs,batteries:loadBatt,tyres:loadTyre,fuses:loadFuses,inspect:()=>document.getElementById('inspectType').value==='pre_purchase'&&loadChecklist(),torque:loadTorque,analytics:loadAnalytics,tax:loadBizCard,settings:loadSettings,dashboard:loadDashboard};
if(loaders[name])try{loaders[name]();}catch(e){console.error(e);}}
function toggleTheme(){document.body.classList.toggle('dark');const d=document.body.classList.contains('dark');localStorage.setItem('theme',d?'dark':'light');document.getElementById('themeBtn').textContent=d?'☀️':'🌙';}
if(localStorage.getItem('theme')==='dark'){document.body.classList.add('dark');document.getElementById('themeBtn').textContent='☀️';}
async function loadDemo(){if(!confirm('Load sample data?'))return;try{const r=await jpost('/api/demo/seed',{});if(r.success){alert('✓ Demo loaded!\n\n'+r.counts.customers+' customers\n'+r.counts.jobs+' jobs\n'+r.counts.staff+' staff\n'+r.counts.inventory+' items');location.reload();}else{alert('Failed');}}catch(e){alert('Error: '+e.message);}}
async function clearDemo(){if(!confirm('Remove demo data? (Real data stays)'))return;try{const r=await jpost('/api/demo/clear',{});if(r.success){const t=Object.values(r.cleared).reduce((a,b)=>a+b,0);alert('✓ Removed '+t+' demo records');location.reload();}}catch(e){alert('Error: '+e.message);}}
let LANG=localStorage.getItem('lang')||'en';
async function loadLang(){try{await fetch('/api/translations/'+LANG);document.getElementById('langSel').value=LANG;}catch(e){}}
function setLang(){LANG=document.getElementById('langSel').value;localStorage.setItem('lang',LANG);loadLang();}
loadLang();
async function checkStatus(){try{await fetch('/health');document.getElementById('status').innerHTML='<span class="status-online">✓ Backend Online</span>';}catch(e){document.getElementById('status').innerHTML='<span class="status-offline">✗ Backend Offline</span>';}}
checkStatus();
function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML;}
async function jget(u){const r=await fetch(u);return r.json();}
async function jpost(u,b){const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return r.json();}
async function jput(u,b){const r=await fetch(u,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return r.json();}
async function jdel(u){const r=await fetch(u,{method:'DELETE'});return r.json();}
function compressImage(file,maxWidth,quality){return new Promise((resolve)=>{const reader=new FileReader();reader.onload=(e)=>{const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');let{width,height}=img;if(width>maxWidth){height=(height*maxWidth)/width;width=maxWidth;}canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(img,0,0,width,height);resolve(canvas.toDataURL('image/jpeg',quality));};img.src=e.target.result;};reader.readAsDataURL(file);});}
let sigPad=null,sigCtx=null,sigDrawing=false,sigData='';
function openSignature(){const modal=document.createElement('div');modal.id='sigModal';modal.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.75);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px';modal.innerHTML='<div style="background:white;border-radius:20px;padding:20px;width:100%;max-width:500px"><h3 style="color:#E65100;margin-bottom:12px">✍️ Signature</h3><canvas id="sigPad" width="440" height="200" style="border:2px dashed #ddd;border-radius:12px;width:100%;touch-action:none;background:white"></canvas><div style="margin-top:14px;display:flex;gap:8px"><button class="btn-sm gray" onclick="clearSig()" style="flex:1">Clear</button><button class="btn-sm green" onclick="saveSig()" style="flex:1">Confirm</button><button class="btn-sm red" onclick="closeSig()" style="flex:1">Cancel</button></div></div>';document.body.appendChild(modal);sigPad=document.getElementById('sigPad');sigCtx=sigPad.getContext('2d');sigCtx.strokeStyle='#000';sigCtx.lineWidth=2.5;sigCtx.lineCap='round';const start=(e)=>{sigDrawing=true;sigCtx.beginPath();const p=getPos(e);sigCtx.moveTo(p.x,p.y);e.preventDefault();};const draw=(e)=>{if(!sigDrawing)return;const p=getPos(e);sigCtx.lineTo(p.x,p.y);sigCtx.stroke();e.preventDefault();};const stop=()=>{sigDrawing=false;};const getPos=(e)=>{const rect=sigPad.getBoundingClientRect();const x=(e.touches?e.touches[0].clientX:e.clientX)-rect.left;const y=(e.touches?e.touches[0].clientY:e.clientY)-rect.top;return{x:x*(sigPad.width/rect.width),y:y*(sigPad.height/rect.height)};};sigPad.addEventListener('mousedown',start);sigPad.addEventListener('mousemove',draw);sigPad.addEventListener('mouseup',stop);sigPad.addEventListener('touchstart',start,{passive:false});sigPad.addEventListener('touchmove',draw,{passive:false});sigPad.addEventListener('touchend',stop);}
function clearSig(){sigCtx.clearRect(0,0,sigPad.width,sigPad.height);}
function saveSig(){sigData=sigPad.toDataURL('image/png');document.getElementById('sigPreview').innerHTML='<img src="'+sigData+'" style="width:100%;border:1px solid #ddd;border-radius:12px;background:white">';closeSig();}
function closeSig(){const m=document.getElementById('sigModal');if(m)m.remove();}
let rec=null,isRec=false;
function toggleMic(){if(!('webkitSpeechRecognition'in window)&&!('SpeechRecognition'in window)){alert('Not supported');return;}if(!rec){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new SR();rec.lang='en-ZA';rec.onresult=e=>{document.getElementById('chatInput').value=e.results[0][0].transcript;resetMic();sendMsg();};rec.onerror=resetMic;rec.onend=resetMic;}function resetMic(){isRec=false;document.getElementById('micBtn').classList.remove('recording');document.getElementById('micBtn').textContent='🎤';}if(isRec){rec.stop();resetMic();}else{try{rec.start();isRec=true;document.getElementById('micBtn').classList.add('recording');document.getElementById('micBtn').textContent='⏹';}catch(e){alert(e.message);}}}
async function sendMsg(){const i=document.getElementById('chatInput');const m=i.value.trim();if(!m)return;const b=document.getElementById('chatBox');b.innerHTML+='<div class="msg user">'+esc(m)+'</div>';i.value='';b.scrollTop=b.scrollHeight;b.innerHTML+='<div class="msg ai" id="typ">Thinking...</div>';b.scrollTop=b.scrollHeight;try{const d=await jpost('/api/chat',{message:m});document.getElementById('typ').outerHTML='<div class="msg ai">'+esc(d.reply)+'</div>';}catch(e){document.getElementById('typ').outerHTML='<div class="msg ai">Error</div>';}b.scrollTop=b.scrollHeight;}
let rC=null,jC=null;
async function loadDashboard(){try{const d=await jget('/api/stats');document.getElementById('dashStats').innerHTML='<div class="stats-row"><div class="stat-card blue"><div class="num">'+d.jobs_total+'</div><div class="lbl">Jobs</div></div><div class="stat-card purple"><div class="num">'+d.jobs_open+'</div><div class="lbl">Open</div></div><div class="stat-card green"><div class="num">'+d.jobs_completed+'</div><div class="lbl">Done</div></div><div class="stat-card"><div class="num">'+d.customers+'</div><div class="lbl">Customers</div></div><div class="stat-card green"><div class="num">R'+d.revenue+'</div><div class="lbl">Revenue</div></div><div class="stat-card red"><div class="num">R'+d.expenses+'</div><div class="lbl">Expenses</div></div></div>';if(rC)rC.destroy();const c1=document.getElementById('revenueChart');if(c1)rC=new Chart(c1,{type:'line',data:{labels:d.revenue_labels,datasets:[{data:d.revenue_data,borderColor:'#667eea',backgroundColor:'rgba(102,126,234,.15)',tension:.4,fill:true,borderWidth:3}]},options:{responsive:true,plugins:{legend:{display:false}}}});if(jC)jC.destroy();const c2=document.getElementById('jobChart');if(c2)jC=new Chart(c2,{type:'doughnut',data:{labels:['New','Progress','Done'],datasets:[{data:[d.jobs_new,d.jobs_progress,d.jobs_completed],backgroundColor:['#6b7280','#f59e0b','#10b981'],borderWidth:0}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}});const ls=await jget('/api/inventory/low-stock');document.getElementById('dashLowStock').innerHTML=ls.items.length?ls.items.map(i=>'<div class="list-item">⚠️ <strong>'+esc(i.name)+'</strong> — '+i.qty+' left</div>').join(''):'<p style="color:var(--text2)">✓ All OK</p>';const w=await jget('/api/warranty');const soon=w.warranties.filter(x=>x.status==='active').slice(0,5);document.getElementById('dashWarranty').innerHTML=soon.length?soon.map(x=>'<div class="list-item">⏰ '+esc(x.vehicle)+' — '+x.days_left+' days</div>').join(''):'<p style="color:var(--text2)">None</p>';}catch(e){}}
"""
