P4 = r"""
async function searchCodes(){const q=document.getElementById('codeSearch').value;const c=document.getElementById('codeResults');c.innerHTML='<div class="loading">Loading...</div>';try{const d=await jget('/api/fault-codes?search='+encodeURIComponent(q));c.dataset.loaded='1';c.innerHTML=d.codes.length?d.codes.map(x=>'<div class="card"><h3>'+x.code+'<span class="badge '+x.severity.toLowerCase()+'">'+x.severity+'</span></h3><p><strong>'+esc(x.description)+'</strong></p><p style="color:var(--text2);font-size:12px">'+esc(x.system)+'</p><p style="margin-top:8px"><strong>Causes:</strong></p>'+x.causes.map(y=>'<div class="list-item">• '+esc(y)+'</div>').join('')+'<p style="margin-top:8px"><strong>Steps:</strong></p>'+x.steps.map(y=>'<div class="list-item">• '+esc(y)+'</div>').join('')+'</div>').join(''):'<div class="card"><p>No matches</p></div>';}catch(e){c.innerHTML='<div class="card"><p>Error</p></div>';}}
let probData=[];
async function loadProblems(){const d=await jget('/api/problems');probData=d.problems;document.getElementById('problemList').dataset.loaded='1';filterProblems();}
function filterProblems(){const q=(document.getElementById('problemSearch').value||'').toLowerCase();const f=probData.filter(x=>!q||x.title.toLowerCase().includes(q)||x.system.toLowerCase().includes(q));document.getElementById('problemList').innerHTML=f.length?f.map(x=>'<div class="card"><h3>'+esc(x.title)+'<span class="badge '+x.severity.toLowerCase()+'">'+x.severity+'</span></h3><p style="color:var(--text2);font-size:12px">'+esc(x.system)+'</p><p><strong>Causes:</strong></p>'+x.causes.map(y=>'<div class="list-item">• '+esc(y)+'</div>').join('')+'</div>').join(''):'<div class="card"><p>No matches</p></div>';}
async function decodeVin(){const vin=document.getElementById('vinInput').value.trim().toUpperCase();const c=document.getElementById('vinResult');if(vin.length!==17){c.innerHTML='<div class="card"><p style="color:#ef4444">Must be 17 chars</p></div>';return;}c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/vin/'+vin);if(d.detail){c.innerHTML='<div class="card"><p style="color:#ef4444">'+d.detail+'</p></div>';return;}c.innerHTML='<div class="card"><h3>🔍 Info</h3><p><strong>VIN:</strong> '+d.vin+'</p><p><strong>Manufacturer:</strong> '+d.manufacturer+'</p><p><strong>Country:</strong> '+d.country+'</p><p><strong>Year:</strong> '+d.year+'</p></div>';}catch(e){c.innerHTML='<div class="card"><p>Error</p></div>';}}
let paintB64='';
async function previewPaint(e){const f=e.target.files[0];if(!f)return;paintB64=await compressImage(f,1200,0.75);document.getElementById('paintPreview').innerHTML='<img class="img-preview" src="'+paintB64+'">';}
async function matchPaint(){const btn=document.getElementById('paintBtn');const c=document.getElementById('paintResult');if(!paintB64){c.innerHTML='<div class="card"><p style="color:#ef4444">Select image</p></div>';return;}btn.disabled=true;btn.textContent='🎨 Analyzing...';c.innerHTML='<div class="loading">...</div>';try{const d=await jpost('/api/paint/match',{image_base64:paintB64,vehicle_info:document.getElementById('paintVehicle').value});if(!d.success){c.innerHTML='<div class="card"><p style="color:#ef4444">'+(d.error||'Failed')+'</p></div>';}else{const col=d.detected_colour;let h='<div class="card"><div class="swatch" style="background:'+col.hex_code+'"></div><h3>'+esc(col.name)+'</h3><p><strong>'+esc(col.finish)+'</strong> • '+esc(col.colour_family)+'</p><p style="font-family:monospace">'+col.hex_code+'</p><p>Confidence: <strong>'+d.confidence+'</strong></p></div>';if(d.brand_codes){h+='<div class="card"><h3>Brand Codes</h3>';d.brand_codes.forEach(b=>{h+='<div class="list-item"><strong>'+esc(b.brand)+':</strong> '+esc(b.code)+'</div>';});h+='</div>';}if(d.mixing_formula){const m=d.mixing_formula;h+='<div class="card"><h3>Mixing Formula</h3><p><strong>Base:</strong> '+esc(m.base_colour)+'</p>';if(m.toners)m.toners.forEach(t=>{h+='<div class="list-item">• '+esc(t.name)+': '+esc(t.parts)+'</div>';});h+='<p><strong>Reducer:</strong> '+esc(m.reducer)+'</p></div>';}c.innerHTML=h;}}catch(e){c.innerHTML='<div class="card"><p>Error</p></div>';}btn.disabled=false;btn.textContent='🎨 Match Paint Colour';}
let diagB64='';
async function previewDiag(e){const f=e.target.files[0];if(!f)return;diagB64=await compressImage(f,1200,0.75);document.getElementById('photoPreview').innerHTML='<img class="img-preview" src="'+diagB64+'">';}
async function diagnosePhoto(){const btn=document.getElementById('photoBtn');const c=document.getElementById('photoResult');if(!diagB64){c.innerHTML='<div class="card"><p style="color:#ef4444">Select image</p></div>';return;}btn.disabled=true;btn.textContent='📸 Analyzing...';c.innerHTML='<div class="loading">...</div>';try{const d=await jpost('/api/diagnose/photo',{image_base64:diagB64,vehicle_info:document.getElementById('photoVehicle').value});if(!d.success){c.innerHTML='<div class="card"><p style="color:#ef4444">'+(d.error||'Failed')+'</p></div>';}else{let h='<div class="card"><h3>🔍 '+esc(d.problem||'Detected')+'</h3><p><strong>Confidence:</strong> '+d.confidence+'</p><p>'+esc(d.description||'')+'</p></div>';if(d.possible_causes){h+='<div class="card"><h3>Causes</h3>'+d.possible_causes.map(x=>'<div class="list-item">• '+esc(x)+'</div>').join('')+'</div>';}if(d.diagnostic_steps){h+='<div class="card"><h3>Steps</h3>'+d.diagnostic_steps.map(x=>'<div class="list-item">• '+esc(x)+'</div>').join('')+'</div>';}if(d.safety_warnings){h+='<div class="card" style="background:#fef2f2"><h3 style="color:#dc2626">⚠️ Safety</h3>'+d.safety_warnings.map(x=>'<div class="list-item">⚠ '+esc(x)+'</div>').join('')+'</div>';}c.innerHTML=h;}}catch(e){c.innerHTML='<div class="card"><p>Error</p></div>';}btn.disabled=false;btn.textContent='📸 Analyze Photo';}
let jobPhotos=[];
async function addJobPhotos(e){for(const f of Array.from(e.target.files)){jobPhotos.push(await compressImage(f,1000,0.7));}renderJobThumbs();}
function renderJobThumbs(){document.getElementById('jobPhotoThumbs').innerHTML=jobPhotos.map((p,i)=>'<div class="thumb-wrap"><img class="thumb" src="'+p+'"><button class="thumb-del" onclick="removeJobPhoto('+i+')">×</button></div>').join('');}
function removeJobPhoto(i){jobPhotos.splice(i,1);renderJobThumbs();}
function showJobForm(){document.getElementById('jobForm').style.display='block';}
function hideJobForm(){document.getElementById('jobForm').style.display='none';jobPhotos=[];renderJobThumbs();sigData='';document.getElementById('sigPreview').innerHTML='';}
async function loadStaffDropdown(){try{const d=await jget('/api/staff');const sel=document.getElementById('jobAssigned');sel.innerHTML='<option value="">— Assign —</option>'+d.staff.map(s=>'<option value="'+esc(s.name)+'">'+esc(s.name)+'</option>').join('');}catch(e){}}
async function createJob(){const c=document.getElementById('jobCustomer').value.trim();const v=document.getElementById('jobVehicle').value.trim();const comp=document.getElementById('jobComplaint').value.trim();if(!c||!v||!comp){alert('Fill customer, vehicle, complaint');return;}try{await jpost('/api/jobs',{customer:c,phone:document.getElementById('jobPhone').value,vehicle:v,registration:document.getElementById('jobVehicleReg').value,km:parseInt(document.getElementById('jobKm').value)||0,complaint:comp,assigned_to:document.getElementById('jobAssigned').value,warranty_months:parseInt(document.getElementById('jobWarranty').value)||6,photos:jobPhotos,signature:sigData});['jobCustomer','jobPhone','jobVehicle','jobComplaint','jobVehicleReg','jobKm'].forEach(id=>document.getElementById(id).value='');sigData='';document.getElementById('sigPreview').innerHTML='';hideJobForm();loadJobs();}catch(e){alert(e.message);}}
async function loadJobs(){const c=document.getElementById('jobList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/jobs');if(!d.jobs.length){c.innerHTML='<div class="card"><p>No jobs yet.</p></div>';return;}c.innerHTML=d.jobs.reverse().map(j=>{const s=j.status.toLowerCase().replace(' ','');let ph=j.photos&&j.photos.length?'<div class="thumb-row">'+j.photos.map(p=>'<img class="thumb" src="'+p+'">').join('')+'</div>':'';let cost=j.total?'<div style="margin-top:10px;padding:10px;background:#dcfce7;border-radius:10px;font-size:13px"><strong>💰 Total: R'+j.total.toFixed(2)+'</strong></div>':'';let as=j.assigned_to?'<p style="color:var(--text2);font-size:12px">👷 '+esc(j.assigned_to)+'</p>':'';let sig=j.signature?'<div style="margin-top:10px"><strong style="font-size:12px">Signature:</strong><br><img src="'+j.signature+'" style="width:200px;border:1px solid #ddd;background:white;border-radius:8px"></div>':'';return '<div class="card" id="job-'+j.id+'"><h3>Job #'+j.id+' <span class="badge '+s+'">'+esc(j.status)+'</span></h3><p><strong>'+esc(j.customer)+'</strong></p><p>🚗 '+esc(j.vehicle)+(j.registration?' ('+esc(j.registration)+')':'')+'</p>'+as+'<p style="color:var(--text2)">'+esc(j.complaint)+'</p>'+ph+cost+sig+'<p style="font-size:11px;color:var(--text2);margin-top:6px">'+esc(j.created)+'</p><div class="no-print" style="margin-top:10px"><button class="btn-sm blue" onclick="upJob(\''+j.id+'\',\'In Progress\')">Progress</button><button class="btn-sm green" onclick="upJob(\''+j.id+'\',\'Completed\')">Done</button><button class="btn-sm purple" onclick="setCost(\''+j.id+'\')">💰</button><button class="btn-sm whatsapp" onclick="waJob(\''+j.id+'\')">📱</button><button class="btn-sm gray" onclick="printJob(\''+j.id+'\')">🖨</button></div></div>';}).join('');}catch(e){c.innerHTML='<div class="card"><p>Error</p></div>';}}
async function upJob(id,s){await jput('/api/jobs/'+id,{status:s,note:'Status → '+s});loadJobs();}
async function setCost(id){const h=prompt('Labour hours:','1');if(h===null)return;const p=prompt('Parts cost (R):','0');if(p===null)return;const rate=await getRate();await jpost('/api/jobs/'+id+'/cost',{labour_hours:parseFloat(h),labour_rate:rate,parts_cost:parseFloat(p)});loadJobs();}
async function getRate(){try{const r=await jget('/api/workshop');return r.labour_rate||450;}catch(e){return 450;}}
function waJob(id){jget('/api/jobs').then(d=>{const j=d.jobs.find(x=>x.id==id);if(!j)return;const txt='🔧 *Job #'+j.id+'*\n'+j.customer+'\n'+j.vehicle+'\n'+(j.registration?'Reg: '+j.registration+'\n':'')+'Issue: '+j.complaint+'\nStatus: '+j.status+(j.total?'\nTotal: R'+j.total.toFixed(2):'');window.open('https://wa.me/?text='+encodeURIComponent(txt),'_blank');});}
function printJob(id){const el=document.getElementById('job-'+id);const w=window.open('','','width=800,height=600');w.document.write('<html><head><title>Job #'+id+'</title><style>body{font-family:Arial;padding:20px}h1{color:#E65100}</style></head><body><h1>'+document.getElementById('logoDisplay').textContent+' '+document.getElementById('wsNameDisplay').textContent+' — Job #'+id+'</h1>'+el.innerHTML.replace(/<div class="no-print".*?<\/div>/gs,'')+'</body></html>');w.document.close();setTimeout(()=>w.print(),500);}
function showCustomerForm(){document.getElementById('customerForm').style.display='block';}
function hideCustomerForm(){document.getElementById('customerForm').style.display='none';}
async function createCustomer(){const n=document.getElementById('custName').value.trim();const p=document.getElementById('custPhone').value.trim();if(!n||!p){alert('Name+phone required');return;}await jpost('/api/customers',{name:n,phone:p,email:document.getElementById('custEmail').value,address:document.getElementById('custAddress').value});['custName','custPhone','custEmail','custAddress'].forEach(id=>document.getElementById(id).value='');hideCustomerForm();loadCustomers();}
async function loadCustomers(){const c=document.getElementById('customerList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/customers');c.innerHTML=d.customers.length?d.customers.reverse().map(x=>'<div class="card"><h3>👤 '+esc(x.name)+'</h3><p>📞 '+esc(x.phone)+'</p>'+(x.email?'<p>📧 '+esc(x.email)+'</p>':'')+'<button class="btn-sm whatsapp" onclick="waCust(\''+esc(x.phone)+'\')">📱</button></div>').join(''):'<div class="card"><p>No customers</p></div>';}catch(e){}}
function waCust(p){window.open('https://wa.me/'+p.replace(/\D/g,''),'_blank');}
function showApptForm(){document.getElementById('apptForm').style.display='block';}
function hideApptForm(){document.getElementById('apptForm').style.display='none';}
async function createAppt(){const c=document.getElementById('apptCustomer').value.trim();const d=document.getElementById('apptDate').value;const t=document.getElementById('apptTime').value;if(!c||!d||!t){alert('Customer, date, time required');return;}await jpost('/api/appointments',{customer:c,phone:document.getElementById('apptPhone').value,vehicle:document.getElementById('apptVehicle').value,service:document.getElementById('apptService').value,date:d,time:t});['apptCustomer','apptPhone','apptVehicle','apptService','apptDate','apptTime'].forEach(id=>document.getElementById(id).value='');hideApptForm();loadAppts();}
async function loadAppts(){const c=document.getElementById('apptList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/appointments');const s=d.appointments.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));c.innerHTML=s.length?s.map(a=>'<div class="card"><h3>📅 '+esc(a.date)+' at '+esc(a.time)+'</h3><p><strong>'+esc(a.customer)+'</strong></p>'+(a.vehicle?'<p>🚗 '+esc(a.vehicle)+'</p>':'')+'<button class="btn-sm red" onclick="delAppt(\''+a.id+'\')">Delete</button></div>').join(''):'<div class="card"><p>No appointments</p></div>';}catch(e){}}
async function delAppt(id){if(!confirm('Delete?'))return;await jdel('/api/appointments/'+id);loadAppts();}
function showQuoteForm(){document.getElementById('quoteForm').style.display='block';}
function hideQuoteForm(){document.getElementById('quoteForm').style.display='none';}
async function createQuote(){const c=document.getElementById('qCustomer').value.trim();const d=document.getElementById('qDesc').value.trim();if(!c||!d){alert('Required');return;}await jpost('/api/quotes',{customer:c,vehicle:document.getElementById('qVehicle').value,description:d,labour:parseFloat(document.getElementById('qLabour').value)||0,parts:parseFloat(document.getElementById('qParts').value)||0});['qCustomer','qVehicle','qDesc','qLabour','qParts'].forEach(id=>document.getElementById(id).value='');hideQuoteForm();loadQuotes();}
async function loadQuotes(){const c=document.getElementById('quoteList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/quotes');c.innerHTML=d.quotes.length?d.quotes.reverse().map(q=>'<div class="card"><h3>💬 Quote #'+q.id+'</h3><p><strong>'+esc(q.customer)+'</strong></p><p>'+esc(q.description)+'</p><div class="list-item">Labour: R'+q.labour.toFixed(2)+'</div><div class="list-item">Parts: R'+q.parts.toFixed(2)+'</div><div class="list-item"><strong>Total: R'+q.total.toFixed(2)+'</strong></div><div style="margin-top:10px"><button class="btn-sm green" onclick="acceptQuote(\''+q.id+'\')">→ Invoice</button><button class="btn-sm red" onclick="delQuote(\''+q.id+'\')">Delete</button></div></div>').join(''):'<div class="card"><p>No quotes</p></div>';}catch(e){}}
async function acceptQuote(id){const r=await jpost('/api/quotes/'+id+'/accept',{});if(r.success){alert('Converted');loadQuotes();}}
async function delQuote(id){if(!confirm('Delete?'))return;await jdel('/api/quotes/'+id);loadQuotes();}
function showInvoiceForm(){document.getElementById('invoiceForm').style.display='block';}
function hideInvoiceForm(){document.getElementById('invoiceForm').style.display='none';}
async function createInvoice(){const c=document.getElementById('invCustomer').value.trim();const d=document.getElementById('invDesc').value.trim();if(!c||!d){alert('Required');return;}await jpost('/api/invoices',{customer:c,vehicle:document.getElementById('invVehicle').value,description:d,labour:parseFloat(document.getElementById('invLabour').value)||0,parts:parseFloat(document.getElementById('invParts').value)||0});['invCustomer','invVehicle','invDesc','invLabour','invParts'].forEach(id=>document.getElementById(id).value='');hideInvoiceForm();loadInvoices();}
async function loadInvoices(){const c=document.getElementById('invoiceList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/invoices');c.innerHTML=d.invoices.length?d.invoices.reverse().map(i=>{const s=i.paid?'paid':(i.amount_paid>0?'partial':'outstanding');return '<div class="card" id="inv-'+i.id+'"><h3>Invoice #'+i.id+' <span class="badge '+s+'">'+s.toUpperCase()+'</span></h3><p><strong>'+esc(i.customer)+'</strong></p><p>'+esc(i.description)+'</p><div class="list-item">Labour: R'+i.labour.toFixed(2)+'</div><div class="list-item">Parts: R'+i.parts.toFixed(2)+'</div><div class="list-item"><strong>Total: R'+i.total.toFixed(2)+'</strong></div><div class="list-item">Paid: R'+(i.amount_paid||0).toFixed(2)+' | Balance: R'+(i.total-(i.amount_paid||0)).toFixed(2)+'</div><div class="no-print" style="margin-top:10px"><button class="btn-sm green" onclick="recordPay(\''+i.id+'\')">💰 Pay</button><button class="btn-sm whatsapp" onclick="waInv(\''+i.id+'\')">📱</button><button class="btn-sm blue" onclick="printInv(\''+i.id+'\')">🖨</button></div></div>';}).join(''):'<div class="card"><p>No invoices</p></div>';}catch(e){}}
async function recordPay(id){const a=prompt('Amount received (R):');if(!a)return;await jpost('/api/invoices/'+id+'/pay',{amount:parseFloat(a)});loadInvoices();}
function waInv(id){jget('/api/invoices').then(d=>{const i=d.invoices.find(x=>x.id==id);const txt='🔧 *'+document.getElementById('wsNameDisplay').textContent+'*\nInvoice #'+i.id+'\n'+i.customer+'\n'+i.description+'\nTotal: R'+i.total.toFixed(2);window.open('https://wa.me/?text='+encodeURIComponent(txt),'_blank');});}
function printInv(id){const el=document.getElementById('inv-'+id);const w=window.open('','','width=800,height=600');w.document.write('<html><head><title>Invoice</title><style>body{font-family:Arial;padding:20px}h1{color:#E65100}</style></head><body><h1>'+document.getElementById('logoDisplay').textContent+' '+document.getElementById('wsNameDisplay').textContent+' — Invoice #'+id+'</h1>'+el.innerHTML.replace(/<div class="no-print".*?<\/div>/gs,'')+'</body></html>');w.document.close();setTimeout(()=>w.print(),500);}
let partsData=[];
async function loadParts(){const d=await jget('/api/parts');partsData=d.parts;document.getElementById('partsList').dataset.loaded='1';filterParts();}
function filterParts(){const q=(document.getElementById('partsSearch').value||'').toLowerCase();const f=partsData.filter(x=>!q||x.name.toLowerCase().includes(q)||x.number.toLowerCase().includes(q)||x.brand.toLowerCase().includes(q));document.getElementById('partsList').innerHTML=f.map(p=>'<div class="card"><h3>'+esc(p.name)+'</h3><p style="font-family:monospace;font-size:12px">'+esc(p.number)+'</p><p>'+esc(p.brand)+' | '+esc(p.category)+'</p><p style="font-size:16px;color:var(--primary);font-weight:700">R'+p.price+'</p></div>').join('')||'<div class="card"><p>None</p></div>';}
function showInvForm(){document.getElementById('invForm').style.display='block';}
function hideInvForm(){document.getElementById('invForm').style.display='none';}
async function addInventory(){const n=document.getElementById('invPartName').value.trim();if(!n){alert('Name required');return;}await jpost('/api/inventory',{part_number:document.getElementById('invPartNum').value,name:n,category:document.getElementById('invCategory').value,qty:parseInt(document.getElementById('invQty').value)||0,min_qty:parseInt(document.getElementById('invMinQty').value)||5,cost_price:parseFloat(document.getElementById('invCostPrice').value)||0,sell_price:parseFloat(document.getElementById('invSellPrice').value)||0,supplier:document.getElementById('invSupplier').value});['invPartNum','invPartName','invCategory','invQty','invMinQty','invCostPrice','invSellPrice','invSupplier'].forEach(id=>document.getElementById(id).value='');hideInvForm();loadInventory();}
async function loadInventory(){const c=document.getElementById('inventoryList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/inventory');c.innerHTML=d.items.length?d.items.map(i=>{const cls=i.qty<=i.min_qty?'warn':'ok';return '<div class="card"><h3>'+esc(i.name)+' <span class="badge '+cls+'">'+i.qty+'</span></h3><p style="font-family:monospace;font-size:12px">'+esc(i.part_number||'-')+'</p><p>Cost: R'+i.cost_price.toFixed(2)+' | Sell: R'+i.sell_price.toFixed(2)+'</p><div style="margin-top:10px"><button class="btn-sm green" onclick="adjInv(\''+i.id+'\',1)">+1</button><button class="btn-sm red" onclick="adjInv(\''+i.id+'\',-1)">-1</button><button class="btn-sm gray" onclick="delInv(\''+i.id+'\')">Delete</button></div></div>';}).join(''):'<div class="card"><p>No items</p></div>';}catch(e){}}
async function adjInv(id,d){await jpost('/api/inventory/'+id+'/adjust',{delta:d});loadInventory();}
async function delInv(id){if(!confirm('Delete?'))return;await jdel('/api/inventory/'+id);loadInventory();}
function showPOForm(){document.getElementById('poForm').style.display='block';}
function hidePOForm(){document.getElementById('poForm').style.display='none';}
async function createPO(){const s=document.getElementById('poSupplier').value.trim();const i=document.getElementById('poItems').value.trim();if(!s||!i){alert('Required');return;}await jpost('/api/purchase-orders',{supplier:s,items:i,total:parseFloat(document.getElementById('poTotal').value)||0});['poSupplier','poItems','poTotal'].forEach(id=>document.getElementById(id).value='');hidePOForm();loadPOs();}
async function loadPOs(){const c=document.getElementById('poList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/purchase-orders');c.innerHTML=d.pos.length?d.pos.reverse().map(p=>'<div class="card"><h3>PO #'+p.id+' <span class="badge '+(p.status==='received'?'ok':'new')+'">'+p.status+'</span></h3><p><strong>'+esc(p.supplier)+'</strong></p><p>'+esc(p.items)+'</p><p>Total: R'+p.total.toFixed(2)+'</p><div style="margin-top:10px"><button class="btn-sm green" onclick="markPO(\''+p.id+'\',\'received\')">Received</button><button class="btn-sm red" onclick="delPO(\''+p.id+'\')">Delete</button></div></div>').join(''):'<div class="card"><p>No POs</p></div>';}catch(e){}}
async function markPO(id,s){await jput('/api/purchase-orders/'+id,{status:s});loadPOs();}
async function delPO(id){if(!confirm('Delete?'))return;await jdel('/api/purchase-orders/'+id);loadPOs();}
function showStaffForm(){document.getElementById('staffForm').style.display='block';}
function hideStaffForm(){document.getElementById('staffForm').style.display='none';}
async function addStaff(){const n=document.getElementById('staffName').value.trim();if(!n){alert('Name required');return;}await jpost('/api/staff',{name:n,role:document.getElementById('staffRole').value,phone:document.getElementById('staffPhone').value,email:document.getElementById('staffEmail').value,hourly_rate:parseFloat(document.getElementById('staffRate').value)||150});['staffName','staffRole','staffPhone','staffEmail'].forEach(id=>document.getElementById(id).value='');hideStaffForm();loadStaff();}
async function loadStaff(){const c=document.getElementById('staffList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/staff');c.innerHTML=d.staff.length?d.staff.map(s=>'<div class="card"><h3>👷 '+esc(s.name)+'</h3><p>'+esc(s.role||'-')+'</p>'+(s.phone?'<p>📞 '+esc(s.phone)+'</p>':'')+'<p>Rate: R'+s.hourly_rate.toFixed(2)+'/hr</p><button class="btn-sm red" onclick="delStaff(\''+s.id+'\')">Delete</button></div>').join(''):'<div class="card"><p>No staff</p></div>';}catch(e){}}
async function delStaff(id){if(!confirm('Delete?'))return;await jdel('/api/staff/'+id);loadStaff();}
async function loadClockin(){const c=document.getElementById('clockinList');c.innerHTML='<div class="loading">...</div>';try{const sd=await jget('/api/staff');const cd=await jget('/api/clockins');c.innerHTML=sd.staff.length?sd.staff.map(s=>{const active=cd.clockins.find(x=>x.staff_id===s.id&&!x.clock_out);return '<div class="card"><h3>👷 '+esc(s.name)+'</h3>'+(active?'<p style="color:#10b981;font-weight:700">🕐 In since '+esc(active.clock_in)+'</p><button class="btn-sm red" onclick="clockOut(\''+s.id+'\')">Clock Out</button>':'<button class="btn-sm green" onclick="clockIn(\''+s.id+'\')">Clock In</button>')+'</div>';}).join(''):'<div class="card"><p>Add staff first</p></div>';}catch(e){}}
async function clockIn(id){await jpost('/api/clockins',{staff_id:id});loadClockin();}
async function clockOut(id){await jpost('/api/clockins/'+id+'/out',{});loadClockin();}
function showExpenseForm(){document.getElementById('expenseForm').style.display='block';}
function hideExpenseForm(){document.getElementById('expenseForm').style.display='none';}
async function addExpense(){const a=parseFloat(document.getElementById('expAmount').value)||0;if(!a){alert('Amount required');return;}await jpost('/api/expenses',{category:document.getElementById('expCat').value,amount:a,date:document.getElementById('expDate').value||new Date().toISOString().slice(0,10),note:document.getElementById('expNote').value});['expAmount','expDate','expNote'].forEach(id=>document.getElementById(id).value='');hideExpenseForm();loadExpenses();}
async function loadExpenses(){const c=document.getElementById('expenseList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/expenses');const total=d.expenses.reduce((s,x)=>s+x.amount,0);c.innerHTML='<div class="card" style="background:linear-gradient(135deg,#ef4444,#f87171);color:white"><h3 style="color:white">Total</h3><p style="font-size:26px;color:white;font-weight:800">R'+total.toFixed(2)+'</p></div>'+(d.expenses.length?d.expenses.reverse().map(e=>'<div class="card"><h3>'+esc(e.category)+' <span class="badge new">R'+e.amount.toFixed(2)+'</span></h3><p>'+esc(e.note||'-')+'</p><p style="font-size:11px;color:var(--text2)">'+esc(e.date)+'</p><button class="btn-sm red" onclick="delExp(\''+e.id+'\')">Delete</button></div>').join(''):'<div class="card"><p>No expenses</p></div>');}catch(e){}}
async function delExp(id){if(!confirm('Delete?'))return;await jdel('/api/expenses/'+id);loadExpenses();}
function showFuelForm(){document.getElementById('fuelForm').style.display='block';}
function hideFuelForm(){document.getElementById('fuelForm').style.display='none';}
async function addFuel(){const v=document.getElementById('fuelVehicle').value.trim();const km=parseInt(document.getElementById('fuelKm').value)||0;const l=parseFloat(document.getElementById('fuelLitres').value)||0;if(!v||!km||!l){alert('Vehicle, km, litres');return;}await jpost('/api/fuel',{vehicle:v,km:km,litres:l,cost:parseFloat(document.getElementById('fuelCost').value)||0,station:document.getElementById('fuelStation').value,date:document.getElementById('fuelDate').value||new Date().toISOString().slice(0,10)});['fuelVehicle','fuelKm','fuelLitres','fuelCost','fuelStation','fuelDate'].forEach(id=>document.getElementById(id).value='');hideFuelForm();loadFuel();}
async function loadFuel(){const c=document.getElementById('fuelList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/fuel');c.innerHTML=d.logs.length?d.logs.reverse().map(f=>'<div class="card"><h3>⛽ '+esc(f.vehicle)+'</h3><div class="list-item">Odometer: <strong>'+f.km+' km</strong></div><div class="list-item">Litres: <strong>'+f.litres+' L</strong></div><div class="list-item">Cost: <strong>R'+f.cost.toFixed(2)+'</strong></div>'+(f.consumption>0?'<div class="list-item">Consumption: <strong style="color:#10b981">'+f.consumption+' L/100km</strong></div>':'')+'<button class="btn-sm red" onclick="delFuel(\''+f.id+'\')">Delete</button></div>').join(''):'<div class="card"><p>No fuel logs</p></div>';}catch(e){}}
async function delFuel(id){if(!confirm('Delete?'))return;await jdel('/api/fuel/'+id);loadFuel();}
async function loadWarranty(){const c=document.getElementById('warrantyList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/warranty');c.innerHTML=d.warranties.length?d.warranties.map(w=>{const cls=w.status==='active'?'ok':'warn';return '<div class="card"><h3>🎁 '+esc(w.vehicle)+' <span class="badge '+cls+'">'+w.status.toUpperCase()+'</span></h3><p><strong>'+esc(w.customer)+'</strong></p><div class="list-item">Job #'+w.id+' on '+esc(w.job_date)+'</div><div class="list-item">Warranty: '+w.months+' months</div><div class="list-item">Expires: <strong>'+esc(w.expiry)+'</strong></div><div class="list-item">'+(w.days_left>0?'<span style="color:#10b981">Expires in '+w.days_left+' days</span>':'<span style="color:#ef4444">Expired '+Math.abs(w.days_left)+' days ago</span>')+'</div></div>';}).join(''):'<div class="card"><p>No warranties</p></div>';}catch(e){}}
async function loadReminders(){const c=document.getElementById('remindersList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/reminders');c.innerHTML=d.reminders.length?d.reminders.map(r=>'<div class="card"><h3>🗓️ '+esc(r.vehicle)+'</h3><p>'+esc(r.customer)+'</p><p>Due: <strong>'+esc(r.due)+'</strong></p><button class="btn-sm whatsapp" onclick="remindWA(\''+esc(r.phone||'')+'\',\''+esc(r.customer)+'\',\''+esc(r.vehicle)+'\')">📱 Remind</button></div>').join(''):'<div class="card"><p>None due</p></div>';}catch(e){}}
function remindWA(phone,name,vehicle){const txt='Hi '+name+', your '+vehicle+' is due for service.';window.open(phone?'https://wa.me/'+phone.replace(/\D/g,'')+'?text='+encodeURIComponent(txt):'https://wa.me/?text='+encodeURIComponent(txt),'_blank');}
let wiringData=[];
async function loadWiring(){const d=await jget('/api/wiring');wiringData=d.circuits;filterWiring();}
function filterWiring(){const q=(document.getElementById('wiringSearch').value||'').toLowerCase();const f=wiringData.filter(x=>!q||x.name.toLowerCase().includes(q)||x.system.toLowerCase().includes(q));document.getElementById('wiringList').innerHTML=f.map(w=>'<div class="card"><h3>🔌 '+esc(w.name)+'</h3><p style="font-size:12px;color:var(--text2)">'+esc(w.system)+'</p><p><strong>Components:</strong></p>'+w.components.map(c=>'<div class="list-item">• '+esc(c)+'</div>').join('')+'<p><strong>Connections:</strong></p>'+w.connections.map(c=>'<div class="list-item" style="font-family:monospace;font-size:11px">'+esc(c)+'</div>').join('')+'</div>').join('')||'<div class="card"><p>None</p></div>';}
let obdData=[];
async function loadOBD(){const d=await jget('/api/obd-pids');obdData=d.pids;filterOBD();}
function filterOBD(){const q=(document.getElementById('obdSearch').value||'').toLowerCase();const f=obdData.filter(x=>!q||x.name.toLowerCase().includes(q)||x.pid.includes(q));document.getElementById('obdList').innerHTML='<table class="torque-table"><tr><th>PID</th><th>Name</th><th>Desc</th></tr>'+f.map(x=>'<tr><td><strong>'+x.pid+'</strong></td><td>'+esc(x.name)+'</td><td style="font-size:11px">'+esc(x.desc)+'</td></tr>').join('')+'</table>';}
let bulbsData=[];
async function loadBulbs(){const d=await jget('/api/bulbs');bulbsData=d.bulbs;filterBulbs();}
function filterBulbs(){const q=(document.getElementById('bulbSearch').value||'').toLowerCase();const f=bulbsData.filter(x=>!q||x.vehicle.toLowerCase().includes(q));document.getElementById('bulbList').innerHTML=f.map(b=>'<div class="card"><h3>💡 '+esc(b.vehicle)+'</h3><div class="list-item">Low: <strong>'+esc(b.headlight_low)+'</strong></div><div class="list-item">High: <strong>'+esc(b.headlight_high)+'</strong></div></div>').join('')||'<div class="card"><p>None</p></div>';}
let battData=[];
async function loadBatt(){const d=await jget('/api/batteries');battData=d.batteries;filterBatt();}
function filterBatt(){const q=(document.getElementById('battSearch').value||'').toLowerCase();const f=battData.filter(x=>!q||x.vehicle.toLowerCase().includes(q));document.getElementById('battList').innerHTML=f.map(b=>'<div class="card"><h3>🔋 '+esc(b.vehicle)+'</h3><div class="list-item">Group: <strong>'+esc(b.group)+'</strong></div><div class="list-item">CCA: <strong>'+b.cca+'</strong></div><div class="list-item">Ah: <strong>'+b.ah+'</strong></div></div>').join('')||'<div class="card"><p>None</p></div>';}
let tyreData=[];
async function loadTyre(){const d=await jget('/api/tyres');tyreData=d.tyres;filterTyre();}
function filterTyre(){const q=(document.getElementById('tyreSearch').value||'').toLowerCase();const f=tyreData.filter(x=>!q||x.vehicle.toLowerCase().includes(q));document.getElementById('tyreList').innerHTML=f.map(t=>'<div class="card"><h3>🛞 '+esc(t.vehicle)+'</h3><div class="list-item">Size: <strong>'+esc(t.size)+'</strong></div><div class="list-item">Front: <strong>'+esc(t.pressure_f)+'</strong></div><div class="list-item">Rear: <strong>'+esc(t.pressure_r)+'</strong></div></div>').join('')||'<div class="card"><p>None</p></div>';}
async function loadFuses(){const c=document.getElementById('fuseList');c.innerHTML='<div class="loading">...</div>';try{const d=await jget('/api/fuses');c.innerHTML=d.fuses.map(f=>'<div class="card"><h3>🔌 '+esc(f.vehicle)+'</h3><p style="font-size:12px;color:var(--text2)">'+esc(f.location)+'</p>'+f.common.map(x=>'<div class="list-item">• '+esc(x)+'</div>').join('')+'</div>').join('');}catch(e){}}
async function calcService(){const km=parseInt(document.getElementById('svcKm').value)||0;const t=document.getElementById('svcType').value;if(!km){alert('Enter km');return;}const d=await jpost('/api/service-calc',{current_km:km,vehicle_type:t});document.getElementById('svcResult').innerHTML='<div class="card" style="background:linear-gradient(135deg,#4facfe,#00f2fe);color:white"><h3 style="color:white">Next Service</h3><p style="font-size:28px;font-weight:800;color:white">at '+d.next_service_km+' km</p></div><div class="card"><h3>Items</h3>'+d.items.map(i=>'<div class="list-item">• '+esc(i)+'</div>').join('')+'</div>';}
async function loadChecklist(){const t=document.getElementById('inspectType').value;const d=await jget('/api/checklists/'+t);document.getElementById('inspectList').innerHTML='<div class="card"><h3>'+esc(d.name)+'</h3>'+d.items.map((x,i)=>'<div class="checklist-item"><input type="checkbox" id="chk'+i+'"><label for="chk'+i+'">'+esc(x)+'</label></div>').join('')+'</div>';}
function printChecklist(){const w=window.open('','','width=800,height=600');w.document.write('<html><head><title>Checklist</title></head><body style="padding:20px"><h1>'+document.getElementById('wsNameDisplay').textContent+'</h1>'+document.getElementById('inspectList').innerHTML+'</body></html>');w.document.close();setTimeout(()=>w.print(),500);}
async function calcTorque(){const d=await jpost('/api/bolt-calc',{size:document.getElementById('boltSize').value,grade:document.getElementById('boltGrade').value,condition:document.getElementById('boltCondition').value});document.getElementById('boltResult').innerHTML='<div class="card" style="background:linear-gradient(135deg,#667eea,#764ba2);color:white"><h3 style="color:white">Recommended</h3><p style="font-size:32px;font-weight:800;color:white;margin:8px 0">'+d.nm.toFixed(1)+' Nm</p><p style="color:white">'+d.ftlb.toFixed(1)+' ft·lb</p></div>';}
let torqueData=[],seqData=[];
async function loadTorque(){if(!torqueData.length){const d=await jget('/api/torque');torqueData=d.bolts;seqData=d.sequences;}filterTorque();}
function filterTorque(){const q=(document.getElementById('torqueSearch').value||'').toLowerCase();const f=torqueData.filter(x=>!q||x.size.toLowerCase().includes(q)||x.grade.toLowerCase().includes(q));document.getElementById('torqueTable').innerHTML='<table class="torque-table"><tr><th>Size</th><th>Grade</th><th>Nm</th><th>ft·lb</th><th>Use</th></tr>'+f.map(x=>'<tr><td><strong>'+esc(x.size)+'</strong></td><td>'+esc(x.grade)+'</td><td>'+x.nm+'</td><td>'+x.ftlb+'</td><td>'+esc(x.use)+'</td></tr>').join('')+'</table>';document.getElementById('torqueSeq').innerHTML=seqData.map(s=>'<div class="card"><h3>'+esc(s.component)+'</h3>'+s.steps.map(x=>'<div class="list-item">• '+esc(x)+'</div>').join('')+'</div>').join('');}
async function searchVehicleHistory(){const q=document.getElementById('vehicleSearch').value.trim().toLowerCase();const c=document.getElementById('vehicleHistory');if(!q){c.innerHTML='<div class="loading">Enter search</div>';return;}const d=await jget('/api/jobs');const m=d.jobs.filter(j=>j.vehicle.toLowerCase().includes(q)||(j.registration||'').toLowerCase().includes(q));c.innerHTML=m.length?'<p style="margin-bottom:12px;color:var(--text2)">'+m.length+' record(s)</p>'+m.reverse().map(j=>'<div class="card"><h3>Job #'+j.id+'</h3><p><strong>'+esc(j.customer)+'</strong></p><p>🚗 '+esc(j.vehicle)+'</p><p>'+esc(j.complaint)+'</p><p><span class="badge '+j.status.toLowerCase().replace(' ','')+'">'+esc(j.status)+'</span></p></div>').join(''):'<div class="card"><p>No history</p></div>';}
async function loadAnalytics(){const d=await jget('/api/analytics');let h='<div class="stats-row"><div class="stat-card blue"><div class="num">R'+d.avg_invoice.toFixed(0)+'</div><div class="lbl">Avg Invoice</div></div><div class="stat-card green"><div class="num">R'+d.total_revenue.toFixed(0)+'</div><div class="lbl">Revenue</div></div><div class="stat-card red"><div class="num">R'+d.total_expenses.toFixed(0)+'</div><div class="lbl">Expenses</div></div><div class="stat-card purple"><div class="num">R'+d.net_profit.toFixed(0)+'</div><div class="lbl">Net</div></div></div>';if(d.top_services.length)h+='<div class="card"><h3>🔥 Top Services</h3>'+d.top_services.map(s=>'<div class="list-item"><strong>'+esc(s.name)+'</strong> — '+s.count+'×</div>').join('')+'</div>';if(d.top_customers.length)h+='<div class="card"><h3>⭐ Top Customers</h3>'+d.top_customers.map(x=>'<div class="list-item"><strong>'+esc(x.name)+'</strong> — R'+x.total.toFixed(0)+'</div>').join('')+'</div>';document.getElementById('analyticsContent').innerHTML=h;}
async function loadBizCard(){const d=await jget('/api/workshop');document.getElementById('bcLogo').textContent=d.logo||'🔧';document.getElementById('bcName').textContent=d.name||'My Workshop';document.getElementById('bcPhone').textContent=d.phone||'';document.getElementById('bcAddress').textContent=d.address||'';}
function downloadTax(){const f=document.getElementById('taxFrom').value;const t=document.getElementById('taxTo').value;window.location.href='/api/export/tax?from_date='+f+'&to_date='+t;}
function printBizCard(){const w=window.open('','','width=600,height=400');w.document.write('<html><head><title>Card</title></head><body style="padding:20px">'+document.getElementById('bizCard').outerHTML+'</body></html>');w.document.close();setTimeout(()=>w.print(),500);}
async function loadSettings(){const d=await jget('/api/workshop');document.getElementById('wsLogo').value=d.logo||'🔧';document.getElementById('wsName').value=d.name||'';document.getElementById('wsPhone').value=d.phone||'';document.getElementById('wsAddress').value=d.address||'';document.getElementById('wsEmail').value=d.email||'';document.getElementById('wsRate').value=d.labour_rate||450;applyBranding(d);}
function applyBranding(d){document.getElementById('logoDisplay').textContent=d.logo||'🔧';document.getElementById('wsNameDisplay').textContent=(d.name||'RAMSTECH').toUpperCase();const sub=[d.phone,d.address].filter(Boolean).join(' • ');document.getElementById('wsSubtitle').textContent=sub||'AI Workshop Assistant v10.1';}
async function saveSettings(){const p={logo:document.getElementById('wsLogo').value||'🔧',name:document.getElementById('wsName').value,phone:document.getElementById('wsPhone').value,address:document.getElementById('wsAddress').value,email:document.getElementById('wsEmail').value,labour_rate:parseFloat(document.getElementById('wsRate').value)||450};await jpost('/api/workshop',p);applyBranding(p);alert('Saved ✓');}
loadSettings();
function exportJobsCSV(){window.location.href='/api/export/jobs';}
function exportCustomersCSV(){window.location.href='/api/export/customers';}
</script>
</body>
</html>"""
